name: Build

on:
  push:
    branches: [ main, dev/*, release/*, develop ]
  pull_request:
    branches: [ main, dev/*, release/*, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        dotnet build
        dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish /home/runner/work/bordertale/bordertale/bordertale -r win-x64 -p:PublishSingleFile=true --configuration Release --self-contained true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: latest
        path: /home/runner/work/bordertale/bordertale/bordertale/bin/Release/net5.0/win-x64/publish/

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v2
      - name: Discord Notifier
        if: ${{ github.event_name != 'pull_request' }}
        uses: fateyan/action-discord-notifier@v1.2.0
        with:
          message-title: New Commits Pushed
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
